#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const defaults = {
  jsonOutPath: path.join(repoRoot, "reports/failure_mode_analysis_v33.json"),
  mdOutPath: path.join(repoRoot, "reports/FAILURE_MODE_ANALYSIS_V33.md")
};

function parseArgs(args) {
  const parsed = { ...defaults };
  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--json-out") parsed.jsonOutPath = path.resolve(args[++index]);
    else if (arg === "--md-out") parsed.mdOutPath = path.resolve(args[++index]);
  }
  return parsed;
}

function readText(relativePath) {
  const fullPath = path.join(repoRoot, relativePath);
  return fs.existsSync(fullPath) ? fs.readFileSync(fullPath, "utf8") : "";
}

function readJson(relativePath) {
  const fullPath = path.join(repoRoot, relativePath);
  return fs.existsSync(fullPath) ? JSON.parse(fs.readFileSync(fullPath, "utf8")) : null;
}

function countCode(markdown, code) {
  const pattern = new RegExp(`\\|\\s*(?:fail|warn)\\s*\\|[^\\n]*\\|\\s*${code.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*\\|`, "g");
  return (markdown.match(pattern) || []).length;
}

function metricSummary(roundPath) {
  const round = readJson(roundPath);
  const rows = round?.results || [];
  const qwen = rows.filter((row) => !row.deterministic);
  const values = (items, key) => items.map((row) => Number(row[key])).filter(Number.isFinite).sort((a, b) => a - b);
  const avg = (items, key) => {
    const list = values(items, key);
    return list.length ? list.reduce((sum, value) => sum + value, 0) / list.length : null;
  };
  const p95 = (items, key) => {
    const list = values(items, key);
    return list.length ? list[Math.min(list.length - 1, Math.ceil(list.length * 0.95) - 1)] : null;
  };
  return {
    result_count: rows.length,
    deterministic_count: rows.filter((row) => row.deterministic).length,
    qwen_count: qwen.length,
    avg_total_ms: avg(rows, "total_latency_ms"),
    qwen_avg_total_ms: avg(qwen, "total_latency_ms"),
    qwen_p95_total_ms: p95(qwen, "total_latency_ms"),
    qwen_slow_gt_10s: qwen.filter((row) => Number(row.total_latency_ms) > 10000).length
  };
}

function gateSummary(pathValue) {
  const report = readJson(pathValue);
  return report?.gate || null;
}

export function buildFailureModeAnalysis() {
  const round01Md = readText("reports/WEBLLM_ROUND_01.md");
  const round02Md = readText("reports/WEBLLM_ROUND_02_200.md");
  const v31Misreading = gateSummary("reports/misreading_v31_safe_body_300.json");
  const v32Misreading = gateSummary("reports/misreading_v32_300.json");
  const v33Misreading = gateSummary("reports/misreading_v33_300.json");
  const v31 = metricSummary("reports/webllm_round_03_latency300_v31_safe_body.json");
  const v32 = metricSummary("reports/webllm_round_03_latency300_v32_guarded_prose_budgeted_generation.json");
  const v33 = metricSummary("reports/webllm_round_03_latency300_v33_postprocessed_prose.json");

  const rows = [
    {
      removed_layer: "deterministic refusal lane",
      controlled_layer: "refusal_expected answers are bypassed to a fixed refusal phrase",
      expected_failure_mode: "model answers when evidence contract requires refusal",
      observed_without_layer: `Round 01: ${countCode(round01Md, "G002_refusal_missing")} G002 refusal failures; 2 context-window runtime errors also show prompt-only routing fragility.`,
      observed_with_layer: "V3.3 latency300: deterministic refusal rows complete with contract fail/warn = 0/0.",
      source_reports: ["reports/WEBLLM_ROUND_01.md", "reports/WEBLLM_ROUND_03_LATENCY300_V33_POSTPROCESSED_PROSE.md"]
    },
    {
      removed_layer: "deterministic source/rights lane",
      controlled_layer: "source_rights_question answers are assembled from evidence fields",
      expected_failure_mode: "rights/source labels missing, truncated, interpreted, or mismatched",
      observed_without_layer: `Round 01/02: ${countCode(round01Md, "G005_unverified_field_assertion") + countCode(round02Md, "G005_unverified_field_assertion")} G005 unverified field assertions, ${countCode(round02Md, "G006_source_rights_tag_missing")} G006 missing source-rights tags, and ${countCode(round02Md, "G007_source_rights_tag_mismatch")} G007 tag mismatches.`,
      observed_with_layer: "V3.3 latency300: source/rights rows are deterministic hybrid rows; contract fail/warn = 0/0.",
      source_reports: ["reports/WEBLLM_ROUND_01.md", "reports/WEBLLM_ROUND_02_200.md", "reports/WEBLLM_ROUND_03_LATENCY300_V33_POSTPROCESSED_PROSE.md"]
    },
    {
      removed_layer: "post-generation evidence tag injection",
      controlled_layer: "EVIDENCE TAGS are injected by code instead of generated by the model",
      expected_failure_mode: "required fields are implicit, omitted, or copied imprecisely",
      observed_without_layer: `Round 02 200: 61 contract failures and 146 warnings; ${countCode(round02Md, "G101_required_field_value_not_observed")} G101 required-field visibility warnings.`,
      observed_with_layer: "V3.3 latency300: contract fail/warn = 0/0 because required tags are exact evidence-derived strings.",
      source_reports: ["reports/WEBLLM_ROUND_02_200.md", "reports/WEBLLM_ROUND_03_LATENCY300_V33_POSTPROCESSED_PROSE.md"]
    },
    {
      removed_layer: "post-generation prose polisher",
      controlled_layer: "polish_prose weakens absolute/first claims and inserts source-limited hedge",
      expected_failure_mode: "overconfidence and unsupported first/earliest language leak into delivered prose",
      observed_without_layer: `V3.1 safe-body 300: ${v31Misreading?.overconfidence_answer_count ?? "unknown"}/${v31Misreading?.evaluated_answer_count ?? "unknown"} overconfidence answers.`,
      observed_with_layer: `V3.3 latency300: ${v33Misreading?.overconfidence_answer_count ?? "unknown"} overconfidence, ${v33Misreading?.unwarranted_inference_answer_count ?? "unknown"} unwarranted inference; guardrail compliance pass.`,
      source_reports: ["reports/misreading_v31_safe_body_300.json", "reports/misreading_v33_300.json", "reports/GUARDRAIL_COMPLIANCE_V33_300.md"]
    },
    {
      removed_layer: "prompt-heavy guardrails",
      controlled_layer: "quality enforced by post-processing rather than long negative instructions",
      expected_failure_mode: "prompt-only guardrails preserve quality but inflate latency",
      observed_without_layer: `V3.2 guarded prose: Qwen avg total ${Math.round(v32.qwen_avg_total_ms ?? 0)} ms, P95 ${Math.round(v32.qwen_p95_total_ms ?? 0)} ms, slow >10s ${v32.qwen_slow_gt_10s}.`,
      observed_with_layer: `V3.3 postprocessed prose: Qwen avg total ${Math.round(v33.qwen_avg_total_ms ?? 0)} ms, P95 ${Math.round(v33.qwen_p95_total_ms ?? 0)} ms, slow >10s ${v33.qwen_slow_gt_10s}; quality gates still pass.`,
      source_reports: ["reports/WEBLLM_ROUND_03_LATENCY300_V32_GUARDED_PROSE_BUDGETED_GENERATION.md", "reports/WEBLLM_ROUND_03_LATENCY300_V33_POSTPROCESSED_PROSE.md"]
    },
    {
      removed_layer: "evidence pruning / compact value-only packets",
      controlled_layer: "model sees compact value summaries while tags preserve exact fields",
      expected_failure_mode: "larger prompts increase TTFT and long-tail latency",
      observed_without_layer: `Earlier less-pruned variants show higher generation cost; V3.1 safe body Qwen avg total ${Math.round(v31.qwen_avg_total_ms ?? 0)} ms and P95 ${Math.round(v31.qwen_p95_total_ms ?? 0)} ms.`,
      observed_with_layer: `V3.3 Qwen avg TTFT is reported separately in latency300 output and Qwen P95 total is ${Math.round(v33.qwen_p95_total_ms ?? 0)} ms.`,
      source_reports: ["reports/WEBLLM_ROUND_03_LATENCY300_V31_SAFE_BODY.md", "reports/WEBLLM_ROUND_03_LATENCY300_V33_POSTPROCESSED_PROSE.md"]
    }
  ];

  return {
    generated_at: new Date().toISOString(),
    summary: {
      purpose: "Show why each reliability/latency layer is necessary rather than decorative.",
      row_count: rows.length
    },
    supporting_metrics: {
      round01: {
        g002_refusal_missing: countCode(round01Md, "G002_refusal_missing"),
        g005_unverified_field_assertion: countCode(round01Md, "G005_unverified_field_assertion")
      },
      round02_200: {
        g101_required_field_value_not_observed: countCode(round02Md, "G101_required_field_value_not_observed"),
        g005_unverified_field_assertion: countCode(round02Md, "G005_unverified_field_assertion"),
        g006_source_rights_tag_missing: countCode(round02Md, "G006_source_rights_tag_missing"),
        g007_source_rights_tag_mismatch: countCode(round02Md, "G007_source_rights_tag_mismatch")
      },
      v31_safe_body: { latency: v31, misreading: v31Misreading },
      v32_guarded_prose: { latency: v32, misreading: v32Misreading },
      v33_postprocessed_prose: { latency: v33, misreading: v33Misreading }
    },
    rows
  };
}

function markdown(report) {
  const table = report.rows.map((row) => `| ${row.removed_layer} | ${row.expected_failure_mode} | ${row.observed_without_layer} | ${row.observed_with_layer} |`).join("\n");
  return `# V3.3 Failure Mode And Layer Necessity Analysis

Generated: ${report.generated_at}

This report organizes existing experiment evidence into a layer-removal
ablation table. It is intended for the paper's failure-mode analysis section:
the point is not only that the final system works, but that each layer prevents
a previously observed failure class.

## Summary

- Rows: ${report.summary.row_count}
- Purpose: ${report.summary.purpose}

## Layer Removal Table

| Removed layer | Expected failure mode | Observed without layer | Observed with final layer |
|---|---|---|---|
${table}

## Notes For Paper

- Treat deterministic-lane latency and model-generation latency separately.
- The source/rights and refusal rows demonstrate system reliability, not Qwen
  generation skill.
- The V3.2 to V3.3 comparison is the clearest evidence that prompt-heavy
  guardrails are not the only way to obtain cautious prose.
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const options = parseArgs(process.argv.slice(2));
  const report = buildFailureModeAnalysis();
  fs.writeFileSync(options.jsonOutPath, `${JSON.stringify(report, null, 2)}\n`);
  fs.writeFileSync(options.mdOutPath, markdown(report));
  console.log(JSON.stringify({
    json: path.relative(repoRoot, options.jsonOutPath),
    md: path.relative(repoRoot, options.mdOutPath),
    rows: report.summary.row_count
  }, null, 2));
}
